name: Convert Markdown to PDF
on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  convert:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Pandoc
        run: |
          sudo apt-get install -y pandoc texlive-latex-base texlive-fonts-recommended
      - name: Convert to PDF
        run: |
          pandoc README.md -o README.pdf --pdf-engine=xelatex
      - name: Upload PDF
        uses: actions/upload-artifact@v4
        with:
          name: pdf-file
          path: README.pdf